basePath: /api/v1
consumes:
- application/json
definitions:
  EmailLoginRequest:
    properties:
      email:
        type: string
        x-go-name: Email
      password:
        type: string
        x-go-name: Password
    required:
    - email
    - password
    type: object
    x-go-package: github.com/solabsafrica/afrikanest/restful/request
  ErrorResponse:
    properties:
      message:
        type: string
        x-go-name: Message
      stack_trace:
        type: string
        x-go-name: StackTrace
      title:
        type: string
        x-go-name: Title
      type:
        type: string
        x-go-name: Type
    type: object
    x-go-package: github.com/solabsafrica/afrikanest/restful/response
  GetUserResponse:
    properties:
      email:
        type: string
        x-go-name: Email
      first_name:
        type: string
        x-go-name: FirstName
      id:
        type: string
        x-go-name: ID
      last_name:
        type: string
        x-go-name: LastName
      name:
        type: string
        x-go-name: Name
      phone:
        type: string
        x-go-name: Phone
    type: object
    x-go-package: github.com/solabsafrica/afrikanest/restful/response
  LoginResponse:
    properties:
      token:
        type: string
        x-go-name: Token
    type: object
    x-go-package: github.com/solabsafrica/afrikanest/restful/response
  RefreshTokenRequest:
    properties:
      token:
        type: string
        x-go-name: Token
    type: object
    x-go-package: github.com/solabsafrica/afrikanest/restful/request
  UpdateUserRequest:
    properties:
      email:
        type: string
        x-go-name: Email
      first_name:
        type: string
        x-go-name: FirstName
      id:
        type: string
        x-go-name: ID
      last_name:
        type: string
        x-go-name: LastName
      phone:
        type: string
        x-go-name: Phone
    type: object
    x-go-package: github.com/solabsafrica/afrikanest/restful/request
  UpdateUserResponse:
    properties:
      id:
        type: string
        x-go-name: ID
      updated_at:
        type: string
        x-go-name: UpdatedAt
    type: object
    x-go-package: github.com/solabsafrica/afrikanest/restful/response
host: localhost:8081
info:
  description: Documentation of AFRIKANEST API.
  title: afrikanest.
  version: 1.0.0
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a user and returns an access token
      operationId: loginUser
      parameters:
      - description: desc
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/EmailLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: LoginResponse
          schema:
            $ref: '#/definitions/LoginResponse'
        "401":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - auth
  /me:
    get:
      consumes:
      - application/json
      description: Get current user
      operationId: getCurrentUser
      produces:
      - application/json
      responses:
        "200":
          description: GetUserResponse
          schema:
            $ref: '#/definitions/GetUserResponse'
        "401":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - user
  /user/{id}:
    put:
      consumes:
      - application/json
      description: Update user
      operationId: updateUser
      parameters:
      - description: desc
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/UpdateUserRequest'
      - in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      produces:
      - application/json
      responses:
        "200":
          description: UpdateUserResponse
          schema:
            $ref: '#/definitions/UpdateUserResponse'
        "401":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - user
produces:
- application/json
schemes:
- http
security:
- bearerAuth:
  - '[]'
securityDefinitions:
  apiKey:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"
